ebbe_test_specification:
    resource: "@EbbeTestSpecificationBundle/Resources/config/routing.yml"
    prefix:   /

ebbe_tagging:
    resource: "@EbbeTaggingBundle/Resources/config/routing.yml"
    prefix:   /

ebbe_test_planning:
    resource: "@EbbeTestPlanningBundle/Resources/config/routing.yml"
    prefix:   /

ebbe_test_evaluation:
    resource: "@EbbeTestEvaluationBundle/Resources/config/routing.yml"
    prefix:   /

ebbe_test_mission:
    resource: "@EbbeTestMissionBundle/Resources/config/routing.yml"
    prefix:   /

ebbe_config_mgt:
    resource: "@EbbeConfigMgtBundle/Resources/config/routing.yml"
    prefix:   /


admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
