raep_config_mgt:
    resource: "@RaepConfigMgtBundle/Resources/config/routing.yml"
    prefix:   /

raep_test_spec:
    resource: "@RaepTestSpecBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
