<?php

namespace Ebbe\SubjectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VersionItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersionItemRepository extends EntityRepository
{
}
