parameters:
#    ebbe_config_mgt.example.class: Ebbe\ConfigMgtBundle\Example

services:
#    ebbe_config_mgt.example:
#        class: %ebbe_config_mgt.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
