<?php

namespace Raep\TestSpecBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TestCaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestCaseRepository extends EntityRepository
{
}
