<?php

namespace Ebbe\Test\TopicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FocusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FocusRepository extends EntityRepository
{
}
