<?php

namespace Ebbe\Test\MissionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CaseAssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaseAssignmentRepository extends EntityRepository
{
}
