# Raep/ConfigMgtBundle/Resources/config/admin.yml

services:
    sonata.admin.post:
        class: Raep\ConfigMgtBundle\Admin\SubjectAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Configuration Management", label: "Subject" }
        arguments:
            - ~
            - Raep\ConfigMgtBundle\Entity\Subject
            - ~
        calls:
            - [ setTranslationDomain, [RaepConfigMgtBundle]]
