<?php

namespace Ebbe\ConfigMgtBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BuildupVersionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildupVersionRepository extends EntityRepository
{
}
